'''
Customized Scenarios and Routes
'''


# customized non-default center transforms for actors ['waypoint_ratio', 'absolute_location']

customized_bounds_and_distributions = {
    "default": {
        "customized_parameters_bounds": {},
        "customized_parameters_distributions": {},
        "customized_center_transforms": {},
        "customized_constraints": [],
    },
    "turn_left_town01": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 1,
            "num_of_vehicles_max": 1,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {},
        "customized_constraints": [],
    },
    "go_straight_town07": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 2,
            "num_of_pedestrians_max": 2,
            "num_of_vehicles_min": 2,
            "num_of_vehicles_max": 2,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {},
        "customized_constraints": [],
    },
    "go_straight_town07_one_ped": {
        "customized_parameters_bounds": {
            "friction_min": 0.9,
            "friction_max": 0.9,

            "num_of_weathers_min": 0,
            "num_of_weathers_max": 0,

            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 0,
            "num_of_vehicles_max": 0,

            "pedestrian_x_min_0": -10,
            "pedestrian_x_max_0": 10,
            "pedestrian_y_min_0": -10,
            "pedestrian_y_max_0": 10,
            "pedestrian_speed_min_0": 1,
            "pedestrian_speed_max_0": 5,
            "pedestrian_trigger_distance_min_0": 10,
            "pedestrian_trigger_distance_max_0": 10,
            "pedestrian_dist_to_travel_min_0": 20,
            "pedestrian_dist_to_travel_max_0": 20,
            "num_of_pedestrian_types_min_0": 0,
            "num_of_pedestrian_types_max_0": 0,


            # "vehicle_x_min_0": -10,
            # "vehicle_x_max_0": 10,
            # "vehicle_y_min_0": -2,
            # "vehicle_y_max_0": 2,

        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
        "pedestrian_center_transform_0": ("waypoint_ratio", 50),
        # "vehicle_center_transform_0": ("waypoint_ratio", 50)
        },
        "customized_constraints": [],
    },
    "turn_left_town07_one_ped_and_one_vehicle": {
        "customized_parameters_bounds": {
            "friction_min": 0.9,
            "friction_max": 0.9,

            "num_of_weathers_min": 0,
            "num_of_weathers_max": 0,

            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 1,
            "num_of_vehicles_max": 1,

            "pedestrian_x_min_0": 7,
            "pedestrian_x_max_0": 13,
            "pedestrian_y_min_0": -3,
            "pedestrian_y_max_0": 2,
            "pedestrian_speed_min_0": 1,
            "pedestrian_speed_max_0": 5,
            "pedestrian_trigger_distance_min_0": 10,
            "pedestrian_trigger_distance_max_0": 10,
            "pedestrian_dist_to_travel_min_0": 20,
            "pedestrian_dist_to_travel_max_0": 20,
            "num_of_pedestrian_types_min_0": 0,
            "num_of_pedestrian_types_max_0": 0,



            "vehicle_x_min_0": 3.5,
            "vehicle_x_max_0": 3.5,
            "vehicle_y_min_0": 0,
            "vehicle_y_max_0": 10,
            "vehicle_speed_min_0": 1,
            "vehicle_speed_max_0": 5,
            "vehicle_trigger_distance_min_0": 20,
            "vehicle_trigger_distance_max_0": 20,
            "vehicle_dist_to_travel_min_0": 20,
            "vehicle_dist_to_travel_max_0": 20,
            "num_of_vehicle_types_min_0": 0,
            "num_of_vehicle_types_max_0": 0,
            "vehicle_initial_speed_min_0": 2,
            "vehicle_initial_speed_max_0": 7,
            "vehicle_targeted_speed_min_0": 2,
            "vehicle_targeted_speed_max_0": 7,
            "vehicle_trigger_distance_min_0": 5,
            "vehicle_trigger_distance_max_0": 20,
            "vehicle_avoid_collision_min_0": 1,
            "vehicle_avoid_collision_max_0": 1,
            "vehicle_dist_to_travel_min_0": 10,
            "vehicle_dist_to_travel_max_0": 30,

            "num_of_vehicle_colors_min_0": 0,
            "num_of_vehicle_colors_max_0": 0,
            "vehicle_targeted_yaw_min_0": 10,
            "vehicle_targeted_yaw_max_0": 30,


        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
        "pedestrian_center_transform_0": ("waypoint_ratio", 50),
        "vehicle_center_transform_0": ("waypoint_ratio", 75)
        },
        "customized_constraints": [],
    },
    "leading_car_braking_town05": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 1,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 2,
            "num_of_vehicles_min": 1,
            "num_of_vehicles_max": 2,
            "static_y_max_0": 5,
            "vehicle_x_min_0": -0.5,
            "vehicle_x_max_0": 0.5,
            "vehicle_y_min_0": -12,
            "vehicle_y_max_0": -5,
            "vehicle_y_max_1": 5,
            "vehicle_initial_speed_min_0": 2,
            "vehicle_initial_speed_max_0": 5,
            "vehicle_targeted_speed_min_0": 0,
            "vehicle_targeted_speed_max_0": 2,
            "vehicle_trigger_distance_min_0": 5,
            "vehicle_trigger_distance_max_0": 12,
            "vehicle_avoid_collision_min_0": 1,
            "vehicle_avoid_collision_max_0": 1,
            "vehicle_avoid_collision_min_1": 1,
            "vehicle_avoid_collision_max_1": 1,
            "vehicle_dist_to_travel_min_0": 5,
            "vehicle_dist_to_travel_max_0": 30,
            "vehicle_yaw_min_0": 270,
            "vehicle_yaw_max_0": 270,
        },
        "customized_parameters_distributions": {
            "vehicle_x_0": ("normal", None, 0.5),
            "vehicle_y_0": ("normal", None, 4),
        },
        "customized_center_transforms": {
            "vehicle_center_transform_0": ("waypoint_ratio", 0)
        },
        "customized_constraints": [
            {
                "coefficients": [1, 1],
                "labels": ["vehicle_y_0", "vehicle_trigger_distance_0"],
                "value": 0,
            }
        ],
    },
    "leading_car_braking_town05_fixed_npc_num": {
        "customized_parameters_bounds": {
            "friction_min": 0.9,
            "friction_max": 0.9,
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 1,
            "num_of_vehicles_max": 1,
            "vehicle_x_min_0": -0.5,
            "vehicle_x_max_0": 0.5,
            "vehicle_y_min_0": -12,
            "vehicle_y_max_0": -5,
            "vehicle_initial_speed_min_0": 2,
            "vehicle_initial_speed_max_0": 5,
            "vehicle_targeted_speed_min_0": 0,
            "vehicle_targeted_speed_max_0": 2,
            "vehicle_trigger_distance_min_0": 5,
            "vehicle_trigger_distance_max_0": 12,
            "vehicle_avoid_collision_min_0": 1,
            "vehicle_avoid_collision_max_0": 1,
            "vehicle_dist_to_travel_min_0": 5,
            "vehicle_dist_to_travel_max_0": 30,
            "vehicle_yaw_min_0": 270,
            "vehicle_yaw_max_0": 270,
        },
        "customized_parameters_distributions": {
            "vehicle_x_0": ("normal", None, 0.5),
            "vehicle_y_0": ("normal", None, 4),
        },
        "customized_center_transforms": {
            "vehicle_center_transform_0": ("waypoint_ratio", 0)
        },
        "customized_constraints": [
            {
                "coefficients": [1, 1],
                "labels": ["vehicle_y_0", "vehicle_trigger_distance_0"],
                "value": 0,
            }
        ],
    },
    "turn_left_town05": {
        "customized_parameters_bounds": {
            "friction_min": 0.9,
            "friction_max": 0.9,

            "num_of_weathers_min": 0,
            "num_of_weathers_max": 0,

            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 1,
            "num_of_vehicles_max": 1,

            "pedestrian_x_min_0": -7,
            "pedestrian_x_max_0": 7,
            "pedestrian_y_min_0": -7,
            "pedestrian_y_max_0": 7,
            "pedestrian_yaw_min_0": 0,
            "pedestrian_yaw_max_0": 360,
            "pedestrian_speed_min_0": 1,
            "pedestrian_speed_max_0": 5,
            "pedestrian_trigger_distance_min_0": 5,
            "pedestrian_trigger_distance_max_0": 15,
            "pedestrian_dist_to_travel_min_0": 50,
            "pedestrian_dist_to_travel_max_0": 50,
            "num_of_pedestrian_types_min_0": 0,
            "num_of_pedestrian_types_max_0": 0,

            "vehicle_x_min_0": -4,
            "vehicle_x_max_0": 4,
            "vehicle_y_min_0": -50,
            "vehicle_y_max_0": -10,
            "vehicle_yaw_min_0": 90,
            "vehicle_yaw_max_0": 90,
            "vehicle_trigger_distance_min_0": 10,
            "vehicle_trigger_distance_max_0": 50,
            "vehicle_dist_to_travel_min_0": 90,
            "vehicle_dist_to_travel_max_0": 90,
            "num_of_vehicle_types_min_0": 1,
            "num_of_vehicle_types_max_0": 1,
            "vehicle_initial_speed_min_0": 0,
            "vehicle_initial_speed_max_0": 0,
            "vehicle_targeted_speed_min_0": 3,
            "vehicle_targeted_speed_max_0": 9,
            "vehicle_avoid_collision_min_0": 1,
            "vehicle_avoid_collision_max_0": 1,
            "num_of_vehicle_colors_min_0": 1,
            "num_of_vehicle_colors_max_0": 1,

            "vehicle_waypoint_follower_min_0": 0,
            "vehicle_waypoint_follower_max_0": 0,

            "vehicle_targeted_x_min_0": -5,
            "vehicle_targeted_x_max_0": -5,
            "vehicle_targeted_y_min_0": 50,
            "vehicle_targeted_y_max_0": 50,
            "vehicle_targeted_yaw_min_0": 90,
            "vehicle_targeted_yaw_max_0": 90,

            # "vehicle_waypoint_follower_min_0": 1,
            # "vehicle_waypoint_follower_max_0": 1,
            #
            # "vehicle_targeted_x_min_0": -15,
            # "vehicle_targeted_x_max_0": -15,
            # "vehicle_targeted_y_min_0": 25,
            # "vehicle_targeted_y_max_0": 25,
            # "vehicle_targeted_yaw_min_0": 90,
            # "vehicle_targeted_yaw_max_0": 90

        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
        "pedestrian_center_transform_0": ("waypoint_ratio", 85),
        "vehicle_center_transform_0": ("waypoint_ratio", 50)
        },
        "customized_constraints": [],
    },
    "change_lane_town05": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 1,
            "num_of_pedestrians_min": 0,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 1,
            "num_of_vehicles_max": 3,
            "vehicle_x_min_0": -4,
            "vehicle_x_max_0": -3,
            "vehicle_y_min_0": -20,
            "vehicle_y_max_0": 20,
            "vehicle_yaw_min_0": 270,
            "vehicle_yaw_max_0": 270,
            "vehicle_initial_speed_min_0": 3,
            "vehicle_initial_speed_max_0": 7,
            "vehicle_trigger_distance_min_0": 0,
            "vehicle_trigger_distance_max_0": 0,
            "vehicle_dist_to_travel_min_0": 30,
            "vehicle_dist_to_travel_max_0": 50,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "vehicle_center_transform_0": ("waypoint_ratio", 0)
        },
        "customized_constraints": [],
    },
    "change_lane_town05_fixed_npc_num": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 1,
            "num_of_vehicles_max": 1,
            "vehicle_x_min_0": -4.5,
            "vehicle_x_max_0": -2.5,
            "vehicle_y_min_0": -25,
            "vehicle_y_max_0": 10,
            "vehicle_yaw_min_0": 270,
            "vehicle_yaw_max_0": 270,
            "vehicle_initial_speed_min_0": 2,
            "vehicle_initial_speed_max_0": 8,
            "vehicle_trigger_distance_min_0": 0,
            "vehicle_trigger_distance_max_0": 0,
            "vehicle_dist_to_travel_min_0": 15,
            "vehicle_dist_to_travel_max_0": 40,
            "vehicle_avoid_collision_min_0": 1,
            "vehicle_avoid_collision_max_0": 1,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "vehicle_center_transform_0": ("waypoint_ratio", 0),
            "pedestrian_center_transform_0": ("waypoint_ratio", 50),
        },
        "customized_constraints": [],
    },
    "pedestrians_cross_street_town04": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 10,
            "num_of_pedestrians_max": 10,
            "num_of_vehicles_min": 0,
            "num_of_vehicles_max": 0,
            # "vehicle_waypoint_follower_min_0": 1,
            # "vehicle_waypoint_follower_max_0": 1,
            # "vehicle_waypoint_follower_min_1": 1,
            # "vehicle_waypoint_follower_max_1": 1,
            # "vehicle_waypoint_follower_min_2": 1,
            # "vehicle_waypoint_follower_max_2": 1,
            # "vehicle_waypoint_follower_min_3": 1,
            # "vehicle_waypoint_follower_max_3": 1,
            # "vehicle_waypoint_follower_min_4": 1,
            # "vehicle_waypoint_follower_max_4": 1,
            # "vehicle_waypoint_follower_min_5": 1,
            # "vehicle_waypoint_follower_max_5": 1,
            # "vehicle_waypoint_follower_min_6": 1,
            # "vehicle_waypoint_follower_max_6": 1,
            # "vehicle_waypoint_follower_min_7": 1,
            # "vehicle_waypoint_follower_max_7": 1,
            # "vehicle_waypoint_follower_min_8": 1,
            # "vehicle_waypoint_follower_max_8": 1,
            # "vehicle_waypoint_follower_min_9": 1,
            # "vehicle_waypoint_follower_max_9": 1,
            # "vehicle_avoid_collision_min_0": 1,
            # "vehicle_avoid_collision_max_0": 1,
            # "vehicle_avoid_collision_min_1": 1,
            # "vehicle_avoid_collision_max_1": 1,
            # "vehicle_avoid_collision_min_2": 1,
            # "vehicle_avoid_collision_max_2": 1,
            # "vehicle_avoid_collision_min_3": 1,
            # "vehicle_avoid_collision_max_3": 1,
            # "vehicle_avoid_collision_min_4": 1,
            # "vehicle_avoid_collision_max_4": 1,
            # "vehicle_avoid_collision_min_5": 1,
            # "vehicle_avoid_collision_max_5": 1,
            # "vehicle_avoid_collision_min_6": 1,
            # "vehicle_avoid_collision_max_6": 1,
            # "vehicle_avoid_collision_min_7": 1,
            # "vehicle_avoid_collision_max_7": 1,
            # "vehicle_avoid_collision_min_8": 1,
            # "vehicle_avoid_collision_max_8": 1,
            # "vehicle_avoid_collision_min_9": 1,
            # "vehicle_avoid_collision_max_9": 1,
            "pedestrian_x_min_0": -12,
            "pedestrian_x_max_0": -4,
            "pedestrian_y_min_0": -20,
            "pedestrian_y_max_0": -10,
            "pedestrian_yaw_min_0": -45,
            "pedestrian_yaw_max_0": 45,
            "pedestrian_speed_min_0": 1,
            "pedestrian_speed_max_0": 5,
            "pedestrian_trigger_distance_min_0": 10,
            "pedestrian_trigger_distance_max_0": 20,
            "pedestrian_dist_to_travel_min_0": 5,
            "pedestrian_dist_to_travel_max_0": 30,
            "pedestrian_x_min_1": -12,
            "pedestrian_x_max_1": -4,
            "pedestrian_y_min_1": -20,
            "pedestrian_y_max_1": -10,
            "pedestrian_yaw_min_1": -45,
            "pedestrian_yaw_max_1": 45,
            "pedestrian_speed_min_1": 1,
            "pedestrian_speed_max_1": 5,
            "pedestrian_trigger_distance_min_1": 10,
            "pedestrian_trigger_distance_max_1": 20,
            "pedestrian_dist_to_travel_min_1": 5,
            "pedestrian_dist_to_travel_max_1": 30,
            "pedestrian_x_min_2": -12,
            "pedestrian_x_max_2": -4,
            "pedestrian_y_min_2": -20,
            "pedestrian_y_max_2": -10,
            "pedestrian_yaw_min_2": -45,
            "pedestrian_yaw_max_2": 45,
            "pedestrian_speed_min_2": 1,
            "pedestrian_speed_max_2": 5,
            "pedestrian_trigger_distance_min_2": 10,
            "pedestrian_trigger_distance_max_2": 20,
            "pedestrian_dist_to_travel_min_2": 5,
            "pedestrian_dist_to_travel_max_2": 30,
            "pedestrian_x_min_3": -12,
            "pedestrian_x_max_3": -4,
            "pedestrian_y_min_3": -20,
            "pedestrian_y_max_3": -10,
            "pedestrian_yaw_min_3": -45,
            "pedestrian_yaw_max_3": 45,
            "pedestrian_speed_min_3": 1,
            "pedestrian_speed_max_3": 5,
            "pedestrian_trigger_distance_min_3": 10,
            "pedestrian_trigger_distance_max_3": 20,
            "pedestrian_dist_to_travel_min_3": 5,
            "pedestrian_dist_to_travel_max_3": 30,
            "pedestrian_x_min_4": -12,
            "pedestrian_x_max_4": -4,
            "pedestrian_y_min_4": -20,
            "pedestrian_y_max_4": -10,
            "pedestrian_yaw_min_4": -45,
            "pedestrian_yaw_max_4": 45,
            "pedestrian_speed_min_4": 1,
            "pedestrian_speed_max_4": 5,
            "pedestrian_trigger_distance_min_4": 10,
            "pedestrian_trigger_distance_max_4": 20,
            "pedestrian_dist_to_travel_min_4": 5,
            "pedestrian_dist_to_travel_max_4": 30,
            "pedestrian_x_min_5": 2,
            "pedestrian_x_max_5": 8,
            "pedestrian_y_min_5": -20,
            "pedestrian_y_max_5": -10,
            "pedestrian_yaw_min_5": 135,
            "pedestrian_yaw_max_5": 225,
            "pedestrian_speed_min_5": 1,
            "pedestrian_speed_max_5": 5,
            "pedestrian_trigger_distance_min_5": 10,
            "pedestrian_trigger_distance_max_5": 20,
            "pedestrian_dist_to_travel_min_5": 5,
            "pedestrian_dist_to_travel_max_5": 30,
            "pedestrian_x_min_6": 2,
            "pedestrian_x_max_6": 8,
            "pedestrian_y_min_6": -20,
            "pedestrian_y_max_6": -10,
            "pedestrian_yaw_min_6": 135,
            "pedestrian_yaw_max_6": 225,
            "pedestrian_speed_min_6": 1,
            "pedestrian_speed_max_6": 5,
            "pedestrian_trigger_distance_min_6": 10,
            "pedestrian_trigger_distance_max_6": 20,
            "pedestrian_dist_to_travel_min_6": 5,
            "pedestrian_dist_to_travel_max_6": 30,
            "pedestrian_x_min_7": 2,
            "pedestrian_x_max_7": 8,
            "pedestrian_y_min_7": -20,
            "pedestrian_y_max_7": -10,
            "pedestrian_yaw_min_7": 135,
            "pedestrian_yaw_max_7": 225,
            "pedestrian_speed_min_7": 1,
            "pedestrian_speed_max_7": 5,
            "pedestrian_trigger_distance_min_7": 10,
            "pedestrian_trigger_distance_max_7": 20,
            "pedestrian_dist_to_travel_min_7": 5,
            "pedestrian_dist_to_travel_max_7": 30,
            "pedestrian_x_min_8": 2,
            "pedestrian_x_max_8": 8,
            "pedestrian_y_min_8": -20,
            "pedestrian_y_max_8": -10,
            "pedestrian_yaw_min_8": 135,
            "pedestrian_yaw_max_8": 225,
            "pedestrian_speed_min_8": 1,
            "pedestrian_speed_max_8": 5,
            "pedestrian_trigger_distance_min_8": 10,
            "pedestrian_trigger_distance_max_8": 20,
            "pedestrian_dist_to_travel_min_8": 5,
            "pedestrian_dist_to_travel_max_8": 30,
            "pedestrian_x_min_9": 2,
            "pedestrian_x_max_9": 8,
            "pedestrian_y_min_9": -20,
            "pedestrian_y_max_9": -10,
            "pedestrian_yaw_min_9": 135,
            "pedestrian_yaw_max_9": 225,
            "pedestrian_speed_min_9": 1,
            "pedestrian_speed_max_9": 5,
            "pedestrian_trigger_distance_min_9": 10,
            "pedestrian_trigger_distance_max_9": 20,
            "pedestrian_dist_to_travel_min_9": 5,
            "pedestrian_dist_to_travel_max_9": 30,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "pedestrian_center_transform_0": ("waypoint_ratio", 0),
            "pedestrian_center_transform_1": ("waypoint_ratio", 0),
            "pedestrian_center_transform_2": ("waypoint_ratio", 0),
            "pedestrian_center_transform_3": ("waypoint_ratio", 0),
            "pedestrian_center_transform_4": ("waypoint_ratio", 0),
            "pedestrian_center_transform_5": ("waypoint_ratio", 0),
            "pedestrian_center_transform_6": ("waypoint_ratio", 0),
            "pedestrian_center_transform_7": ("waypoint_ratio", 0),
            "pedestrian_center_transform_8": ("waypoint_ratio", 0),
            "pedestrian_center_transform_9": ("waypoint_ratio", 0),
        },
        "customized_constraints": [],
    },
    "front_town10": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 1,
            "num_of_vehicles_max": 1,
            "vehicle_x_min_0": 3,
            "vehicle_x_max_0": 20,
            "vehicle_y_min_0": -4.5,
            "vehicle_y_max_0": -2.5,
            "vehicle_yaw_min_0": 0,
            "vehicle_yaw_max_0": 0,
            "vehicle_initial_speed_min_0": 2,
            "vehicle_initial_speed_max_0": 8,
            "vehicle_trigger_distance_min_0": 0,
            "vehicle_trigger_distance_max_0": 0,
            "vehicle_dist_to_travel_min_0": 15,
            "vehicle_dist_to_travel_max_0": 40,
            "vehicle_avoid_collision_min_0": 1,
            "vehicle_avoid_collision_max_0": 1,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "vehicle_center_transform_0": ("waypoint_ratio", 0),
            "pedestrian_center_transform_0": ("waypoint_ratio", 50),
        },
        "customized_constraints": [],
    },
    "highway_town04": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 0,
            "num_of_pedestrians_max": 0,
            "num_of_vehicles_min": 2,
            "num_of_vehicles_max": 5,
            "vehicle_x_min_0": 0,
            "vehicle_x_max_0": 6,
            "vehicle_y_min_0": -3,
            "vehicle_y_max_0": -10,
            "vehicle_yaw_min_0": 270,
            "vehicle_yaw_max_0": 270,
            "vehicle_initial_speed_min_0": 4,
            "vehicle_initial_speed_max_0": 10,
            "vehicle_targeted_speed_min_0": 4,
            "vehicle_targeted_speed_max_0": 10,
            "vehicle_trigger_distance_min_0": 15,
            "vehicle_trigger_distance_max_0": 15,
            "vehicle_dist_to_travel_min_0": 5,
            "vehicle_dist_to_travel_max_0": 30,
            "vehicle_x_min_1": 0,
            "vehicle_x_max_1": 6,
            "vehicle_y_min_1": -3,
            "vehicle_y_max_1": -10,
            "vehicle_yaw_min_1": 270,
            "vehicle_yaw_max_1": 270,
            "vehicle_initial_speed_min_1": 4,
            "vehicle_initial_speed_max_1": 10,
            "vehicle_targeted_speed_min_1": 4,
            "vehicle_targeted_speed_max_1": 10,
            "vehicle_trigger_distance_min_1": 15,
            "vehicle_trigger_distance_max_1": 15,
            "vehicle_dist_to_travel_min_1": 5,
            "vehicle_dist_to_travel_max_1": 30,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "vehicle_center_transform_0": ("waypoint_ratio", 0),
            "vehicle_center_transform_1": ("waypoint_ratio", 0),
        },
        "customized_constraints": [],
    },
    "no_static": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {},
        "customized_constraints": [],
    },
    "one_pedestrians_cross_street_town05": {
        "customized_parameters_bounds": {
            "num_of_weathers_min": 0,
            "num_of_weathers_max": 0,
            "num_of_pedestrian_types_min_0": 12,
            "num_of_pedestrian_types_max_0": 12,
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 0,
            "num_of_vehicles_max": 0,
            "pedestrian_x_min_0": -8,
            "pedestrian_x_max_0": 8,
            "pedestrian_y_min_0": -8,
            "pedestrian_y_max_0": 8,
            "pedestrian_speed_min_0": 1,
            "pedestrian_speed_max_0": 4,
            "pedestrian_trigger_distance_min_0": 3,
            "pedestrian_trigger_distance_max_0": 15,
            "pedestrian_dist_to_travel_min_0": 30,
            "pedestrian_dist_to_travel_max_0": 30,
            "friction_min": 0.9,
            "friction_max": 0.9,
            "ego_car_perturbation_x_min_0": 0,
            "ego_car_perturbation_x_max_0": 0,
            "ego_car_perturbation_x_min_1": 0,
            "ego_car_perturbation_x_max_1": 0,
            "ego_car_perturbation_x_min_2": 0,
            "ego_car_perturbation_x_max_2": 0,
            "ego_car_perturbation_x_min_3": 0,
            "ego_car_perturbation_x_max_3": 0,
            "ego_car_perturbation_x_min_4": 0,
            "ego_car_perturbation_x_max_4": 0,
            "ego_car_perturbation_y_min_0": 0,
            "ego_car_perturbation_y_max_0": 0,
            "ego_car_perturbation_y_min_1": 0,
            "ego_car_perturbation_y_max_1": 0,
            "ego_car_perturbation_y_min_2": 0,
            "ego_car_perturbation_y_max_2": 0,
            "ego_car_perturbation_y_min_3": 0,
            "ego_car_perturbation_y_max_3": 0,
            "ego_car_perturbation_y_min_4": 0,
            "ego_car_perturbation_y_max_4": 0,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "pedestrian_center_transform_0": ("waypoint_ratio", 70),
        },
        "customized_constraints": [],
    },
    "two_pedestrians_cross_street_town05": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 2,
            "num_of_pedestrians_max": 2,
            "num_of_vehicles_min": 0,
            "num_of_vehicles_max": 0,
            "num_of_weathers_min": 0,
            "num_of_weathers_max": 0,
            "pedestrian_x_min_0": -8,
            "pedestrian_x_max_0": 8,
            "pedestrian_y_min_0": -8,
            "pedestrian_y_max_0": 8,
            "pedestrian_speed_min_0": 1,
            "pedestrian_speed_max_0": 5,
            "pedestrian_trigger_distance_min_0": 3,
            "pedestrian_trigger_distance_max_0": 15,
            "pedestrian_dist_to_travel_min_0": 5,
            "pedestrian_dist_to_travel_max_0": 30,
            "pedestrian_x_min_1": -8,
            "pedestrian_x_max_1": 8,
            "pedestrian_y_min_1": -8,
            "pedestrian_y_max_1": 8,
            "pedestrian_speed_min_1": 1,
            "pedestrian_speed_max_1": 5,
            "pedestrian_trigger_distance_min_1": 3,
            "pedestrian_trigger_distance_max_1": 15,
            "pedestrian_dist_to_travel_min_1": 5,
            "pedestrian_dist_to_travel_max_1": 30,
            "friction_min": 0.9,
            "friction_max": 0.9,
            "ego_car_perturbation_x_min_0": 0,
            "ego_car_perturbation_x_max_0": 0,
            "ego_car_perturbation_x_min_1": 0,
            "ego_car_perturbation_x_max_1": 0,
            "ego_car_perturbation_x_min_2": 0,
            "ego_car_perturbation_x_max_2": 0,
            "ego_car_perturbation_x_min_3": 0,
            "ego_car_perturbation_x_max_3": 0,
            "ego_car_perturbation_x_min_4": 0,
            "ego_car_perturbation_x_max_4": 0,
            "ego_car_perturbation_y_min_0": 0,
            "ego_car_perturbation_y_max_0": 0,
            "ego_car_perturbation_y_min_1": 0,
            "ego_car_perturbation_y_max_1": 0,
            "ego_car_perturbation_y_min_2": 0,
            "ego_car_perturbation_y_max_2": 0,
            "ego_car_perturbation_y_min_3": 0,
            "ego_car_perturbation_y_max_3": 0,
            "ego_car_perturbation_y_min_4": 0,
            "ego_car_perturbation_y_max_4": 0,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "pedestrian_center_transform_0": ("waypoint_ratio", 40),
            "pedestrian_center_transform_1": ("waypoint_ratio", 40),
        },
        "customized_constraints": [],
    },
    "default_dense": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 5,
            "num_of_pedestrians_max": 10,
            "num_of_vehicles_min": 10,
            "num_of_vehicles_max": 10,
            "friction_min": 0.9,
            "friction_max": 0.9,
            "vehicle_waypoint_follower_min_0": 1,
            "vehicle_waypoint_follower_max_0": 1,
            "vehicle_avoid_collision_min_0": 1,
            "vehicle_avoid_collision_max_0": 1,
            "vehicle_waypoint_follower_min_1": 1,
            "vehicle_waypoint_follower_max_1": 1,
            "vehicle_avoid_collision_min_1": 1,
            "vehicle_avoid_collision_max_1": 1,
            "vehicle_waypoint_follower_min_2": 1,
            "vehicle_waypoint_follower_max_2": 1,
            "vehicle_avoid_collision_min_2": 1,
            "vehicle_avoid_collision_max_2": 1,
            "vehicle_waypoint_follower_min_3": 1,
            "vehicle_waypoint_follower_max_3": 1,
            "vehicle_avoid_collision_min_3": 1,
            "vehicle_avoid_collision_max_3": 1,
            "vehicle_waypoint_follower_min_4": 1,
            "vehicle_waypoint_follower_max_4": 1,
            "vehicle_avoid_collision_min_4": 1,
            "vehicle_avoid_collision_max_4": 1,
            "vehicle_waypoint_follower_min_5": 1,
            "vehicle_waypoint_follower_max_5": 1,
            "vehicle_avoid_collision_min_5": 1,
            "vehicle_avoid_collision_max_5": 1,
            "vehicle_waypoint_follower_min_6": 1,
            "vehicle_waypoint_follower_max_6": 1,
            "vehicle_avoid_collision_min_6": 1,
            "vehicle_avoid_collision_max_6": 1,
            "vehicle_waypoint_follower_min_7": 1,
            "vehicle_waypoint_follower_max_7": 1,
            "vehicle_avoid_collision_min_7": 1,
            "vehicle_avoid_collision_max_7": 1,
            "vehicle_waypoint_follower_min_8": 1,
            "vehicle_waypoint_follower_max_8": 1,
            "vehicle_avoid_collision_min_8": 1,
            "vehicle_avoid_collision_max_8": 1,
            "vehicle_waypoint_follower_min_9": 1,
            "vehicle_waypoint_follower_max_9": 1,
            "vehicle_avoid_collision_min_9": 1,
            "vehicle_avoid_collision_max_9": 1,
            "vehicle_waypoint_follower_min_10": 1,
            "vehicle_waypoint_follower_max_10": 1,
            "vehicle_avoid_collision_min_10": 1,
            "vehicle_avoid_collision_max_10": 1,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {},
        "customized_constraints": [],
    },
    "pedestrians_only": {
        "customized_parameters_bounds": {
            "friction_min": 0.9,
            "friction_max": 0.9,
            "num_of_weathers_min": 0,
            "num_of_weathers_max": 0,
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 5,
            "num_of_pedestrians_max": 10,
            "num_of_vehicles_min": 0,
            "num_of_vehicles_max": 0,
            "ego_car_perturbation_x_0_min": 0,
            "ego_car_perturbation_x_0_max": 0,
            "ego_car_perturbation_x_1_min": 0,
            "ego_car_perturbation_x_1_max": 0,
            "ego_car_perturbation_x_2_min": 0,
            "ego_car_perturbation_x_2_max": 0,
            "ego_car_perturbation_x_3_min": 0,
            "ego_car_perturbation_x_3_max": 0,
            "ego_car_perturbation_x_4_min": 0,
            "ego_car_perturbation_x_4_max": 0,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {},
        "customized_constraints": [],
    },
    "leading_car_braking_only_car_town05": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 0,
            "num_of_pedestrians_max": 0,
            "num_of_vehicles_min": 1,
            "num_of_vehicles_max": 1,
            "vehicle_x_min_0": -0.5,
            "vehicle_x_max_0": 0.5,
            "vehicle_y_min_0": -10,
            "vehicle_y_max_0": -4,
            "vehicle_initial_speed_min_0": 2,
            "vehicle_initial_speed_max_0": 5,
            "vehicle_targeted_speed_min_0": 0,
            "vehicle_targeted_speed_max_0": 2,
            "vehicle_trigger_distance_min_0": 4,
            "vehicle_trigger_distance_max_0": 10,
            "vehicle_avoid_collision_min_0": 1,
            "vehicle_avoid_collision_max_0": 1,
            "vehicle_dist_to_travel_min_0": 5,
            "vehicle_dist_to_travel_max_0": 30,
            "vehicle_yaw_min_0": 270,
            "vehicle_yaw_max_0": 270,
        },
        "customized_parameters_distributions": {
            "vehicle_x_0": ("normal", None, 0.5),
            "vehicle_y_0": ("normal", None, 4),
        },
        "customized_center_transforms": {
            "vehicle_center_transform_0": ("waypoint_ratio", 0)
        },
        "customized_constraints": [
            {
                "coefficients": [1, 1],
                "labels": ["vehicle_y_0", "vehicle_trigger_distance_0"],
                "value": 0,
            }
        ],
    },
    "two_pedestrians_cross_street_straight_town05": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 6,
            "num_of_pedestrians_max": 6,
            "num_of_vehicles_min": 0,
            "num_of_vehicles_max": 0,
            "pedestrian_x_min_0": -7,
            "pedestrian_x_max_0": 7,
            "pedestrian_y_min_0": -10,
            "pedestrian_y_max_0": -4,
            "pedestrian_x_min_1": -7,
            "pedestrian_x_max_1": 7,
            "pedestrian_y_min_1": -10,
            "pedestrian_y_max_1": -4,
            "pedestrian_x_min_2": -7,
            "pedestrian_x_max_2": 7,
            "pedestrian_y_min_2": -10,
            "pedestrian_y_max_2": -4,
            "pedestrian_x_min_3": -7,
            "pedestrian_x_max_3": 7,
            "pedestrian_y_min_3": -10,
            "pedestrian_y_max_3": -4,
            "pedestrian_x_min_4": -7,
            "pedestrian_x_max_4": 7,
            "pedestrian_y_min_4": -10,
            "pedestrian_y_max_4": -4,
            "pedestrian_x_min_5": -7,
            "pedestrian_x_max_5": 7,
            "pedestrian_y_min_5": -10,
            "pedestrian_y_max_5": -4,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "pedestrian_center_transform_0": ("waypoint_ratio", 0),
            "pedestrian_center_transform_1": ("waypoint_ratio", 0),
        },
        "customized_constraints": [],
    },
    "change_lane_town03_fixed_npc_num": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 1,
            "num_of_vehicles_max": 1,
            "vehicle_x_min_0": 2.5,
            "vehicle_x_max_0": 4.5,
            "vehicle_y_min_0": -20,
            "vehicle_y_max_0": 2,
            "vehicle_yaw_min_0": 270,
            "vehicle_yaw_max_0": 270,
            "vehicle_initial_speed_min_0": 2,
            "vehicle_initial_speed_max_0": 8,
            "vehicle_trigger_distance_min_0": 0,
            "vehicle_trigger_distance_max_0": 0,
            "vehicle_dist_to_travel_min_0": 15,
            "vehicle_dist_to_travel_max_0": 40,
            "vehicle_avoid_collision_min_0": 1,
            "vehicle_avoid_collision_max_0": 1,
            "pedestrian_x_min_0": -8,
            "pedestrian_x_max_0": 8,
            "pedestrian_y_min_0": -8,
            "pedestrian_y_max_0": 8,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "vehicle_center_transform_0": ("waypoint_ratio", 0),
            "pedestrian_center_transform_0": ("waypoint_ratio", 75),
        },
        "customized_constraints": [],
    },
    "none": {
        "customized_parameters_bounds": {
            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 0,
            "num_of_pedestrians_max": 0,
            "num_of_vehicles_min": 0,
            "num_of_vehicles_max": 0,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {},
        "customized_constraints": [],
    },
}


customized_routes = {
    # pick: right turn + leading car stops / slow down, town
    "town05_right_0": {
        "town_name": "Town05",
        "direction": "right",
        "route_id": 0,
        "location_list": [(-120, 30), (-103, 4)],
    },
    # pick: turn left non-siginalized intersection, town
    "town01_left_0": {
        "town_name": "Town01",
        "direction": "left",
        "route_id": 0,
        "location_list": [(89.1, 300.8), (110.4, 330.5)],
    },
    # pick: go through non-signalized intersection, rural
    "town07_front_0": {
        "town_name": "Town07",
        "direction": "front",
        "route_id": 0,
        "location_list": [(-151, -60), (-151, -15)],
    },
    # pick: go through non-signalized intersection, town
    "town04_front_0": {
        "town_name": "Town04",
        "direction": "front",
        "route_id": 0,
        "location_list": [(258, -230), (258, -270)],
    },
    # pick: change lane
    "town03_front_1": {
        "town_name": "Town03",
        "direction": "left",
        "route_id": 0,
        "location_list": [(1.5, 185), (4, 165)],
    },
    # potential pick: change lane, town
    "town05_front_0": {
        "town_name": "Town05",
        "direction": "front",
        "route_id": 0,
        "location_list": [(-120, 60), (-124, 26)],
    },
    # potential pick: go through signalized crossroad
    "town03_front_0": {
        "town_name": "Town03",
        "direction": "front",
        "route_id": 0,
        "location_list": [(9, -105), (9, -155)],
    },
    # potential pick: go across street, town
    "town05_front_1": {
        "town_name": "Town05",
        "direction": "front",
        "route_id": 1,
        "location_list": [(-120, 15), (-120, -20)],
    },
    "town05_left_0": {
        "town_name": "Town05",
        "direction": "left",
        "route_id": 0,
        "location_list": [(-120, 15), (-144, -4)],
    },
    # change lane, city, error: other cars are not moving
    "town10HD_front_0": {
        "town_name": "Town10HD",
        "direction": "front",
        "route_id": 0,
        "location_list": [(-38, 143), (-5, 138)],
    },
    # go through non-signalized intersection, rural, error: other cars are not moving
    "town07_left_0": {
        "town_name": "Town07",
        "direction": "left",
        "route_id": 0,
        "location_list": [(-75, -64), (-102, -42)],
    },
    "town07_left_1": {
        "town_name": "Town07",
        "direction": "left",
        "route_id": 1,
        "location_list": [(-151, -60), (-135, -31)],
    },
    # change lane, highway, error: other cars are not moving
    "town04_front_1": {
        "town_name": "Town04",
        "direction": "front",
        "route_id": 1,
        "location_list": [(8, 256), (11, 216)],
    },
}
