customized_bounds_and_distributions = {
    "default": {
        "customized_parameters_bounds": {},
        "customized_parameters_distributions": {},
        "customized_center_transforms": {},
        "customized_constraints": [],
    },

    "turn_left_one_ped_and_one_vehicle": {
        "customized_parameters_bounds": {

            "hour_min": 12,
            "hour_max": 12,
            "damage_min": 0,
            "damage_max": 0,
            "rain_min": 0,
            "rain_max": 0,
            "fog_min": 0,
            "fog_max": 0,
            "wetness_min": 0,
            "wetness_max": 0,
            "cloudiness_min": 0,
            "cloudiness_max": 0,

            "num_of_vehicles_min": 1,
            "num_of_vehicles_max": 1,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,

            "pedestrian_x_min_0": -5,
            "pedestrian_x_max_0": 5,
            "pedestrian_y_min_0": -5,
            "pedestrian_y_max_0": 5,
            "pedestrian_speed_min_0": 1,
            "pedestrian_speed_max_0": 3,
            "pedestrian_travel_distance_min_0": 0,
            "pedestrian_travel_distance_max_0": 0,
            "pedestrian_yaw_min_0": 0,
            "pedestrian_yaw_max_0": 0,
            "pedestrian_0_idle_min_0": 0,
            "pedestrian_0_idle_max_0": 20,
            # "pedestrian_0_idle_min_0": 1,
            # "pedestrian_0_idle_max_0": 3,
            "pedestrian_0_trigger_distance_min_0": 0,
            "pedestrian_0_trigger_distance_max_0": 0,
            # "pedestrian_0_trigger_distance_min_0": 20,
            # "pedestrian_0_trigger_distance_max_0": 40,
            "pedestrian_0_waypoint_x_min_0": 0,
            "pedestrian_0_waypoint_x_max_0": 0,
            "pedestrian_0_waypoint_y_min_0": 10,
            "pedestrian_0_waypoint_y_max_0": 40,

            "vehicle_x_min_0": 0,
            "vehicle_x_max_0": 0,
            "vehicle_y_min_0": -20,
            "vehicle_y_max_0": 0,
            "vehicle_speed_min_0": 1,
            "vehicle_speed_max_0": 8,
            "vehicle_0_idle_min_0": 0,
            "vehicle_0_idle_max_0": 20,
            "vehicle_0_trigger_distance_min_0": 0,
            "vehicle_0_trigger_distance_max_0": 0,
            # "vehicle_0_trigger_distance_min_0": 20,
            # "vehicle_0_trigger_distance_max_0": 100,
            "vehicle_0_waypoint_x_min_0": 0,
            "vehicle_0_waypoint_x_max_0": 0,
            "vehicle_0_waypoint_y_min_0": 10,
            "vehicle_0_waypoint_y_max_0": 70,

        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "vehicle_center_transform_0": ("absolute_location", 19.4,-2.4,-24.3,359,287,0),
            "pedestrian_center_transform_0": ("absolute_location", -18.2,-1.9,-3.7,0,108,0),
        },
        "customized_constraints": [],
    },

    "one_ped_crossing": {
        "customized_parameters_bounds": {

            "hour_min": 12,
            "hour_max": 12,
            "damage_min": 0,
            "damage_max": 0,
            "rain_min": 0,
            "rain_max": 0,
            "fog_min": 0,
            "fog_max": 0,
            "wetness_min": 0,
            "wetness_max": 0,
            "cloudiness_min": 0,
            "cloudiness_max": 0,

            "pedestrian_x_min_0": 0,
            "pedestrian_x_max_0": 0,
            "pedestrian_y_min_0": 0,
            "pedestrian_y_max_0": 0,
            "pedestrian_speed_min_0": 1,
            "pedestrian_speed_max_0": 5,
            "pedestrian_0_idle_min_0": 1,
            "pedestrian_0_idle_max_0": 7,
            "pedestrian_0_trigger_distance_min_0": 0,
            "pedestrian_0_trigger_distance_max_0": 0,
            "pedestrian_0_waypoint_x_min_0": -2,
            "pedestrian_0_waypoint_x_max_0": 2,
            "pedestrian_0_waypoint_y_min_0": 25,
            "pedestrian_0_waypoint_y_max_0": 40,

            "num_of_vehicles_min": 0,
            "num_of_vehicles_max": 0,

        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            # "pedestrian_center_transform_0": ("absolute_location", -18.2,-1.9,-3.7,0,108,0),
            "pedestrian_center_transform_0": ("absolute_location", -37.9,-1.6,-19.4,0,0,0),
        },
        "customized_constraints": [],
    },


    "one_angle_ped_crossing": {
        "customized_parameters_bounds": {

            "hour_min": 12,
            "hour_max": 12,
            "damage_min": 0,
            "damage_max": 0,
            "rain_min": 0,
            "rain_max": 0,
            "fog_min": 0,
            "fog_max": 0,
            "wetness_min": 0,
            "wetness_max": 0,
            "cloudiness_min": 0,
            "cloudiness_max": 0,

            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 0,
            "num_of_vehicles_max": 0,


            "pedestrian_x_min_0": -7,
            "pedestrian_x_max_0": 7,
            "pedestrian_y_min_0": -7,
            "pedestrian_y_max_0": 7,
            "pedestrian_speed_min_0": 1,
            "pedestrian_speed_max_0": 5,
            "pedestrian_0_idle_min_0": 0,
            "pedestrian_0_idle_max_0": 0,

            "pedestrian_travel_distance_min_0": 50,
            "pedestrian_travel_distance_max_0": 50,
            "pedestrian_yaw_min_0": 0,
            "pedestrian_yaw_max_0": 360,


            "pedestrian_0_trigger_distance_min_0": 20,
            "pedestrian_0_trigger_distance_max_0": 20,
            "pedestrian_0_waypoint_x_min_0": 0,
            "pedestrian_0_waypoint_x_max_0": 0,
            "pedestrian_0_waypoint_y_min_0": 0,
            "pedestrian_0_waypoint_y_max_0": 0,

        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "pedestrian_center_transform_0": ("absolute_location", -13.3,-1.9,-18.7,0,102,0),
        },
        "customized_constraints": [],
    },


    "go_across_junction_sf": {
        "customized_parameters_bounds": {

            "hour_min": 12,
            "hour_max": 12,
            "damage_min": 0,
            "damage_max": 0,
            "rain_min": 0,
            "rain_max": 0,
            "fog_min": 0,
            "fog_max": 0,
            "wetness_min": 0,
            "wetness_max": 0,
            "cloudiness_min": 0,
            "cloudiness_max": 0,

            "num_of_vehicles_min": 2,
            "num_of_vehicles_max": 2,
            "num_of_pedestrians_min": 2,
            "num_of_pedestrians_max": 2,

            "pedestrian_x_min_0": 0,
            "pedestrian_x_max_0": 0,
            "pedestrian_y_min_0": 0,
            "pedestrian_y_max_0": 0,
            "pedestrian_speed_min_0": 1,
            "pedestrian_speed_max_0": 3,
            "pedestrian_0_idle_min_0": 0,
            "pedestrian_0_idle_max_0": 0,
            "pedestrian_0_trigger_distance_min_0": 0,
            "pedestrian_0_trigger_distance_max_0": 0,
            "pedestrian_0_waypoint_x_min_0": 0,
            "pedestrian_0_waypoint_x_max_0": 0,
            "pedestrian_0_waypoint_y_min_0": 0,
            "pedestrian_0_waypoint_y_max_0": 0,
            "pedestrian_0_idle_min_1": 0,
            "pedestrian_0_idle_max_1": 0,
            "pedestrian_0_trigger_distance_min_1": 0,
            "pedestrian_0_trigger_distance_max_1": 0,
            "pedestrian_0_waypoint_x_min_1": 0,
            "pedestrian_0_waypoint_x_max_1": 0,
            "pedestrian_0_waypoint_y_min_1": 0,
            "pedestrian_0_waypoint_y_max_1": 0,

            "pedestrian_x_min_1": 0,
            "pedestrian_x_max_1": 0,
            "pedestrian_y_min_1": 0,
            "pedestrian_y_max_1": 0,
            "pedestrian_speed_min_1": 1,
            "pedestrian_speed_max_1": 3,
            "pedestrian_1_idle_min_0": 0,
            "pedestrian_1_idle_max_0": 0,
            "pedestrian_1_trigger_distance_min_0": 0,
            "pedestrian_1_trigger_distance_max_0": 0,
            "pedestrian_1_waypoint_x_min_0": 0,
            "pedestrian_1_waypoint_x_max_0": 0,
            "pedestrian_1_waypoint_y_min_0": 0,
            "pedestrian_1_waypoint_y_max_0": 0,
            "pedestrian_1_idle_min_1": 0,
            "pedestrian_1_idle_max_1": 0,
            "pedestrian_1_trigger_distance_min_1": 0,
            "pedestrian_1_trigger_distance_max_1": 0,
            "pedestrian_1_waypoint_x_min_1": 0,
            "pedestrian_1_waypoint_x_max_1": 0,
            "pedestrian_1_waypoint_y_min_1": 0,
            "pedestrian_1_waypoint_y_max_1": 0,

            "vehicle_x_min_0": 0,
            "vehicle_x_max_0": 0,
            "vehicle_y_min_0": 0,
            "vehicle_y_max_0": 0,
            "vehicle_speed_min_0": 1,
            "vehicle_speed_max_0": 8,
            "vehicle_0_idle_min_0": 0,
            "vehicle_0_idle_max_0": 0,
            "vehicle_0_trigger_distance_min_0": 0,
            "vehicle_0_trigger_distance_max_0": 0,
            "vehicle_0_waypoint_x_min_0": 0,
            "vehicle_0_waypoint_x_max_0": 0,
            "vehicle_0_waypoint_y_min_0": 0,
            "vehicle_0_waypoint_y_max_0": 0,
            "vehicle_0_idle_min_1": 0,
            "vehicle_0_idle_max_1": 0,
            "vehicle_0_trigger_distance_min_1": 0,
            "vehicle_0_trigger_distance_max_1": 0,
            "vehicle_0_waypoint_x_min_1": 0,
            "vehicle_0_waypoint_x_max_1": 0,
            "vehicle_0_waypoint_y_min_1": 0,
            "vehicle_0_waypoint_y_max_1": 0,

            "vehicle_x_min_1": 0,
            "vehicle_x_max_1": 0,
            "vehicle_y_min_1": 0,
            "vehicle_y_max_1": 0,
            "vehicle_speed_min_1": 1,
            "vehicle_speed_max_1": 8,
            "vehicle_1_idle_min_0": 0,
            "vehicle_1_idle_max_0": 0,
            "vehicle_1_trigger_distance_min_0": 0,
            "vehicle_1_trigger_distance_max_0": 0,
            "vehicle_1_waypoint_x_min_0": 0,
            "vehicle_1_waypoint_x_max_0": 0,
            "vehicle_1_waypoint_y_min_0": 0,
            "vehicle_1_waypoint_y_max_0": 0,
            "vehicle_1_idle_min_1": 0,
            "vehicle_1_idle_max_1": 0,
            "vehicle_1_trigger_distance_min_1": 0,
            "vehicle_1_trigger_distance_max_1": 0,
            "vehicle_1_waypoint_x_min_1": 0,
            "vehicle_1_waypoint_x_max_1": 0,
            "vehicle_1_waypoint_y_min_1": 0,
            "vehicle_1_waypoint_y_max_1": 0,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "vehicle_center_transform_0": ("absolute_location", -661.5,10.2,358.5,0,134,0),
            "vehicle_0_center_transform_0": ("absolute_location", -626.1,10.2,324.6,0,134,0),
            "vehicle_0_center_transform_1": ("absolute_location", -597.5,10.2,345.7,0,44,0),

            "vehicle_center_transform_1": ("absolute_location", -642.7,10.2,340.5,0,134,0),
            "vehicle_1_center_transform_0": ("absolute_location", -622.2,10.2,320.9,0,134,0),
            "vehicle_1_center_transform_1": ("absolute_location", -593.9,10.2,293.9,0,134,0),

            "pedestrian_center_transform_0": ("absolute_location", -650.5,10.3,339.1,0,133,0),
            "pedestrian_0_center_transform_0": ("absolute_location", -639.6,10.3,328.9,0,44,0),
            "pedestrian_0_center_transform_1": ("absolute_location", -626.6,10.3,342.3,0,44,0),

            "pedestrian_center_transform_1": ("absolute_location", -581.8,10.3,296.7,0,309,0),
            "pedestrian_1_center_transform_0": ("absolute_location", -603.1,10.3,317.1,0,224,0),
            "pedestrian_1_center_transform_1": ("absolute_location", -618.1,10.3,301.5,0,226,0),
        },
        "customized_constraints": [],
    },


    "go_across_junction_ba": {
        "customized_parameters_bounds": {

            "hour_min": 12,
            "hour_max": 12,
            "damage_min": 0,
            "damage_max": 0,
            "rain_min": 0,
            "rain_max": 0,
            "fog_min": 0,
            "fog_max": 0,
            "wetness_min": 0,
            "wetness_max": 0,
            "cloudiness_min": 0,
            "cloudiness_max": 0,

            "num_of_vehicles_min": 2,
            "num_of_vehicles_max": 2,
            "num_of_pedestrians_min": 2,
            "num_of_pedestrians_max": 2,

            # "num_of_pedestrian_types_min_0": 0,
            # "num_of_pedestrian_types_max_0": 0,
            # "num_of_pedestrian_types_min_1": 0,
            # "num_of_pedestrian_types_max_1": 0,

            "pedestrian_x_min_0": -2,
            "pedestrian_x_max_0": 2,
            "pedestrian_y_min_0": -2,
            "pedestrian_y_max_0": 2,
            "pedestrian_speed_min_0": 1,
            "pedestrian_speed_max_0": 4,
            "pedestrian_0_idle_min_0": 0,
            "pedestrian_0_idle_max_0": 3,
            "pedestrian_0_trigger_distance_min_0": 0,
            "pedestrian_0_trigger_distance_max_0": 0,
            "pedestrian_0_waypoint_x_min_0": -2,
            "pedestrian_0_waypoint_x_max_0": 2,
            "pedestrian_0_waypoint_y_min_0": -2,
            "pedestrian_0_waypoint_y_max_0": 2,
            "pedestrian_0_idle_min_1": 0,
            "pedestrian_0_idle_max_1": 0,
            "pedestrian_0_trigger_distance_min_1": 0,
            "pedestrian_0_trigger_distance_max_1": 0,
            "pedestrian_0_waypoint_x_min_1": -2,
            "pedestrian_0_waypoint_x_max_1": 2,
            "pedestrian_0_waypoint_y_min_1": -2,
            "pedestrian_0_waypoint_y_max_1": 2,

            "pedestrian_x_min_1": -2,
            "pedestrian_x_max_1": 2,
            "pedestrian_y_min_1": -2,
            "pedestrian_y_max_1": 2,
            "pedestrian_speed_min_1": 1,
            "pedestrian_speed_max_1": 4,
            "pedestrian_1_idle_min_0": 0,
            "pedestrian_1_idle_max_0": 3,
            "pedestrian_1_trigger_distance_min_0": 0,
            "pedestrian_1_trigger_distance_max_0": 0,
            "pedestrian_1_waypoint_x_min_0": -2,
            "pedestrian_1_waypoint_x_max_0": 2,
            "pedestrian_1_waypoint_y_min_0": -2,
            "pedestrian_1_waypoint_y_max_0": 2,
            "pedestrian_1_idle_min_1": 0,
            "pedestrian_1_idle_max_1": 0,
            "pedestrian_1_trigger_distance_min_1": 0,
            "pedestrian_1_trigger_distance_max_1": 0,
            "pedestrian_1_waypoint_x_min_1": -2,
            "pedestrian_1_waypoint_x_max_1": 2,
            "pedestrian_1_waypoint_y_min_1": -2,
            "pedestrian_1_waypoint_y_max_1": 2,

            "vehicle_x_min_0": 0,
            "vehicle_x_max_0": 0,
            "vehicle_y_min_0": -3,
            "vehicle_y_max_0": 3,
            "vehicle_speed_min_0": 1,
            "vehicle_speed_max_0": 8,
            "vehicle_0_idle_min_0": 0,
            "vehicle_0_idle_max_0": 3,
            "vehicle_0_trigger_distance_min_0": 0,
            "vehicle_0_trigger_distance_max_0": 0,
            "vehicle_0_waypoint_x_min_0": 0,
            "vehicle_0_waypoint_x_max_0": 0,
            "vehicle_0_waypoint_y_min_0": -3,
            "vehicle_0_waypoint_y_max_0": 3,
            "vehicle_0_idle_min_1": 0,
            "vehicle_0_idle_max_1": 0,
            "vehicle_0_trigger_distance_min_1": 0,
            "vehicle_0_trigger_distance_max_1": 0,
            "vehicle_0_waypoint_x_min_1": 0,
            "vehicle_0_waypoint_x_max_1": 0,
            "vehicle_0_waypoint_y_min_1": -3,
            "vehicle_0_waypoint_y_max_1": 3,

            # "num_of_vehicle_types_min_0": 0,
            # "num_of_vehicle_types_max_0": 0,

            "vehicle_x_min_1": 0,
            "vehicle_x_max_1": 0,
            "vehicle_y_min_1": -3,
            "vehicle_y_max_1": 3,
            "vehicle_speed_min_1": 1,
            "vehicle_speed_max_1": 8,
            "vehicle_1_idle_min_0": 0,
            "vehicle_1_idle_max_0": 3,
            "vehicle_1_trigger_distance_min_0": 0,
            "vehicle_1_trigger_distance_max_0": 0,
            "vehicle_1_waypoint_x_min_0": 0,
            "vehicle_1_waypoint_x_max_0": 0,
            "vehicle_1_waypoint_y_min_0": -3,
            "vehicle_1_waypoint_y_max_0": 3,
            "vehicle_1_idle_min_1": 0,
            "vehicle_1_idle_max_1": 0,
            "vehicle_1_trigger_distance_min_1": 0,
            "vehicle_1_trigger_distance_max_1": 0,
            "vehicle_1_waypoint_x_min_1": 0,
            "vehicle_1_waypoint_x_max_1": 0,
            "vehicle_1_waypoint_y_min_1": -3,
            "vehicle_1_waypoint_y_max_1": 3,

            # "num_of_vehicle_types_min_1": 4,
            # "num_of_vehicle_types_max_1": 4,
        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
            "vehicle_center_transform_0": ("absolute_location", 357,-7.7,-110.2,359,286,0),
            "vehicle_0_center_transform_0": ("absolute_location", 337.3,-7.4,-106.3,359,286,0),
            "vehicle_0_center_transform_1": ("absolute_location", 324.3,-7.5,-122.8,0,192,0),

            "vehicle_center_transform_1": ("absolute_location", 347.3,-7.5,-107.3,359,285,0),
            "vehicle_1_center_transform_0": ("absolute_location", 329.6,-7.3,-102.6,359,285,0),
            "vehicle_1_center_transform_1": ("absolute_location", 311.3,-7.1,-98.2,359,285,0),

            "pedestrian_center_transform_0": ("absolute_location", 362.1,-7.8,-106.3,359,262,0),
            "pedestrian_0_center_transform_0": ("absolute_location", 350.2,-7.6,-105.7,0,174,0),
            "pedestrian_0_center_transform_1": ("absolute_location", 346.4,-7.7,-117.6,0,185,0),

            "pedestrian_center_transform_1": ("absolute_location", 304.2,-7,-105.5,1,104,0),
            "pedestrian_1_center_transform_0": ("absolute_location", 316,-7.2,-109.4,0,0,0),
            "pedestrian_1_center_transform_1": ("absolute_location", 319.1,-7.1,-96.8,0,11,359),
        },
        "customized_constraints": [],
    },

}
customized_routes = {
    "BorregasAve_forward": {
        "town_name": "BorregasAve",
        "location_list": [(274.1,-6.4,-91.9,1,105,0), (361.6,-7.7,-115.9,1,105,0)],
    },
    "BorregasAve_left": {
        "town_name": "BorregasAve",
        "location_list": [(-50.3399963378906, -1.03600025177002, -9.03000640869141, 0, 104.823371887207, 0), (7.53597784042358, -2.04524087905884, 5.36189842224121, 0.126350626349449, 14.6359872817993, 358.324432373047)],
    },
    "SanFrancisco_forward": {
        "town_name": "SanFrancisco",
        "location_list": [(-591.2, 10.2, 297,0,314,0), (-648.2, 10.2, 351.3, 0, 314, 0)],
    },
}
